name: Build fresh image

on:
    push:
    schedule:
      - cron: "42 03 * * *"

jobs:
    buildandpush:
        runs-on: ubuntu-latest
        name: Build images and push to Docker Hub
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            # https://github.com/marketplace/actions/docker-setup-buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Cache Docker layers
              uses: actions/cache@v3
              with:
                path: /tmp/.buildx-cache
                key: ${{ runner.os }}-buildxK-${{ github.sha }}
                restore-keys: |
                  ${{ runner.os }}-buildxK-
            # https://github.com/docker/login-action#docker-hub
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build latest and push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                context: .
                cache-from: type=local,src=/tmp/.buildx-cache
                cache-to: type=local,dest=/tmp/.buildx-cache-new
                platforms: linux/amd64
                push: true
                tags: deltablot/php-prod:8.1, deltablot/php-prod:latest, deltablot/php-prod:8

            - name: Run vulnerabilities scanner
              uses: anchore/scan-action@v3
              with:
                image: deltablot/php-prod:8.1
                fail-build: true

              # This ugly bit is necessary if you don't want your cache to grow forever
              # till it hits GitHub's limit of 5GB.
              # Temp fix
              # https://github.com/docker/build-push-action/issues/252
              # https://github.com/moby/buildkit/issues/1896
            - name: Move cache
              run: |
                rm -rf /tmp/.buildx-cache
                mv /tmp/.buildx-cache-new /tmp/.buildx-cache
