name: Build fresh image

on:
    push:
    schedule:
      - cron: "42 03 * * *"

jobs:
    buildandpush:
        runs-on: ubuntu-latest
        name: Build images and push to registry
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            # https://github.com/marketplace/actions/docker-setup-buildx
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

                # - name: Cache Docker layers
                #   uses: actions/cache@v3
                #   with:
                #     path: /tmp/.buildxyz-cache
                #     key: ${{ runner.os }}-buildxyK-${{ github.sha }}
                #     restore-keys: |
                #       ${{ runner.os }}-buildxyK-
            # https://github.com/docker/login-action#docker-hub
            - name: Login to registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build latest and push to registry
              uses: docker/build-push-action@v4
              with:
                context: .
                platforms: linux/amd64
                push: true
                tags: ghcr.io/deltablot/php-prod:8.1, ghcr.io/deltablot/php-prod:latest, ghcr.io/deltablot/php-prod:8

            # VULN SCAN
            - name: Run Trivy vulnerability scanner
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: deltablot/php-prod:latest
                format: 'table'
                exit-code: '1'
                ignore-unfixed: true
                vuln-type: 'os,library'
                severity: 'CRITICAL'

              # This ugly bit is necessary if you don't want your cache to grow forever
              # till it hits GitHub's limit of 5GB.
              # Temp fix
              # https://github.com/docker/build-push-action/issues/252
              # https://github.com/moby/buildkit/issues/1896
              #- name: Move cache
              #  run: |
              #    rm -rf /tmp/.buildxy-cache
              #    mv /tmp/.buildxyz-cache-new /tmp/.buildxyz-cache
